https://example1.shotgunstudio.com:
  script_name: sg-cron-datapoint.py
  script_key: 123thisisafakescriptkeyexample456
  global_data_point_entity: CustomNonProjectEntity??
  project_data_point_entity: 
  track_globally:
    - entity_type: HumanUser
      filters: [["sg_status_list", "is", "act"]]
      write_to_field: sg_num_active_human_users
